server:
  port: 80
  servlet:
    context-path: /demo



mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: sjb@12345
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    name: springboot
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    database: 11
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 10
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 10
        #最小空闲
        min-idle: 0
        #连接超时时间
    timeout: 10000
mq:
  topicname: itemstock
  nameserver:
    addr: 192.168.10.177:9876

verifycodeonoff: true


